version: "3.7"
services:
  web:
    image: alexmar/nginx:0.11
    container_name: web
    depends_on:
     - php
    ports:
     - "80:80"
    volumes:
     - ./info.php:/var/www/info.php
    networks:
      front_net:
        ipv4_address: 192.168.0.100
        aliases:
         - web
  
  php:
    image: alexmar/php:0.2
    container_name: php
    ports:
     - "9000:9000"
    volumes:
     - ./info.php:/var/www/info.php
    networks:
      front_net:
        ipv4_address: 192.168.0.200
        aliases:
         - php

networks:
  front_net:
    ipam:
      driver: default
      config:
       - subnet: "192.168.0.0/24"
 
